10seconds_install: Updated to 64 bit GnuPG IDs.

diff --git a/10seconds_install b/10seconds_install
--- a/10seconds_install
+++ b/10seconds_install
@@ -42,14 +42,14 @@ run() {
 	    (fetch -o /dev/null file:///bin/sh && echo fetch -o -) ||
 	    (curl -h >/dev/null && echo curl -L) ||
 	    (wget -h >/dev/null && echo wget -qO -) ||
-	    echo 'No lynx, wget, curl, fetch: Please inform parallel@gnu.org what you use for downloading URLs' >&2
+       	    echo 'No lynx, wget, curl, fetch: Please inform parallel@gnu.org what you use for downloading URLs' >&2
        )
     if test "$get" = ""; then
 	exit 1
     fi
 
     if ! perl -e 1; then
-	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
+ 	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
 	exit 1
     fi
 
@@ -69,31 +69,30 @@ run() {
 	    # GnuPG installed
 	    # Setup .gnupg/gpg.conf if not already done
 	    echo | gpg 2>/dev/null >/dev/null
-	    if gpg --list-keys 0xFFFFFFF1 && gpg --list-keys 0x88888888 ; then
+       	    if gpg --list-keys 0x2C6229E2FFFFFFF1 && gpg --list-keys 0xD1AB451688888888 ; then
 		echo Keys fetched
 		# OK
-       		return 0
+		return 0
 	    else
 		keyservers="keyserver.ubuntu.com
 			    pgp.surf.nl
-			    keyserver.bazon.ru
-			    agora.cenditel.gob.ve
+			    keys.openpgp.org
 			    pgp.benny-baumann.de"
 		for keyserver in $keyservers ; do
-		    if gpg --keyserver "$keyserver" --recv-key 0xFFFFFFF1 &&
-			    gpg --keyserver "$keyserver" --recv-key 0x88888888 ; then
+		    if gpg --keyserver "$keyserver" --recv-key 0x2C6229E2FFFFFFF1 &&
+			    gpg --keyserver "$keyserver" --recv-key 0xD1AB451688888888 ; then
 			# OK
 			return 0
 		    fi
 		done
-     		echo
-       		echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
+		echo
+		echo "Cannot fetch keyID 0xD1AB451688888888, so the signature cannot be checked."
 		return 1
 	    fi
 	else
-       	    # GnuPG not installed
+	    # GnuPG not installed
 	    echo
-  	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
+	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
 	    return 1
 	fi
     }
@@ -103,13 +102,13 @@ run() {
 	if gpg --with-fingerprint "$latest".tar.bz2.sig 2>&1 |
 	       perl -e 'exit not grep /^Primary key fingerprint: BE9C B493 81DE 3166 A3BC..66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610..7E7B D1AB 4516 8888 8888/, <>'; then
 	    # Source code signed by Ole Tange <ole@tange.dk>
-	    # KeyID FFFFFFF1/88888888
+	    # KeyID 0x2C6229E2FFFFFFF1/0xD1AB451688888888
 	    true
 	else
 	    # GnuPG signature failed
 	    echo
 	    echo "The signature on $latest.tar.bz2 is wrong. This may indicate that a criminal has changed the code."
-     	    echo "THIS IS BAD AND THE CODE WILL NOT BE INSTALLED."
+	    echo "THIS IS BAD AND THE CODE WILL NOT BE INSTALLED."
 	    echo
 	    echo "See http://git.savannah.gnu.org/cgit/parallel.git/tree/README for other installation methods."
 	    exit 1
@@ -121,7 +120,7 @@ run() {
 	echo "Continue anyway? (y/n)"
 	read YN </dev/tty
 	if test "$YN" = "n"; then
- 	    # Stop
+	    # Stop
 	    exit 2
 	else
 	    # Continue
@@ -147,12 +146,12 @@ run() {
 	fi
 
 	# Is $HOME/bin already in $PATH?
-	if echo "$PATH" | grep "$HOME"/bin >/dev/null; then
-	    # $HOME/bin is already in $PATH
+       	if echo "$PATH" | grep "$HOME"/bin >/dev/null; then
+  	    # $HOME/bin is already in $PATH
 	    true
 	else
 	    # Add $HOME/bin to $PATH for both bash and csh
-       	    echo 'PATH=$PATH:$HOME/bin' >> "$HOME"/.bashrc
+	    echo 'PATH=$PATH:$HOME/bin' >> "$HOME"/.bashrc
 	    echo 'setenv PATH ${PATH}:${HOME}/bin' >> "$HOME"/.cshrc
 	fi
 
